#!/bin/bash
# Criado por: Dany Sullivan


IP_IMPRESSORA=$1
COR=$2

COR_TONER=$(snmpwalk -c public -v1 $IP_IMPRESSORA .1.3.6.1.2.1.43.11.1.1.6.1 | grep "$COR Toner Cartridge" | cut -d"." -f8 | cut -d" " -f1)
MAX_TONER=$(snmpwalk -c public -v1 $IP_IMPRESSORA .1.3.6.1.2.1.43.11.1.1.9.1.$COR_TONER | cut -d" " -f4)
CAP_TONER=$(snmpwalk -c public -v1 $IP_IMPRESSORA .1.3.6.1.2.1.43.11.1.1.8.1.$COR_TONER | cut -d" " -f4)

STATUS_TONER=$[($MAX_TONER * 100) / $CAP_TONER]

echo $STATUS_TONER
